{% set name = "conda-project" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 31c613554b9c3dee1336d333884617e83b59faac6c8ada17cc6ef904c83e2b2f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - conda-project = conda_project.cli.main:main

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - setuptools
  run:
    - python >=3.8,<3.12
    - conda-lock >=1.2
    - lockfile
    - pexpect
    - ruamel.yaml
    - pydantic
    - shellingham
    - python-dotenv
    - fsspec
    - python-libarchive-c

test:
  imports:
    - conda_project
  commands:
    - conda-project --help
    - python -c "import conda_project; ver = conda_project.__version__; assert ver == \"{{ version }}\""

about:
  home: https://github.com/conda-incubator/conda-project
  summary: Tool for encapsulating, running, and reproducing projects with conda environments
  description: |
    Sharing your work is more than sharing your code in a script file or notebook. To make your
    work properly reproducible, it is necessary to include the list of required third-party
    dependencies, specifications for how to run your code, and any other files that it may need.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://conda-incubator.github.io/conda-project/user_guide.html
  dev_url: https://github.com/conda-incubator/conda-project

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - mattkram
